version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - nastevens
  ignore:
  - dependency-name: bytes
    versions:
    - "> 0.4, < 1"
  - dependency-name: bytes
    versions:
    - ">= 0.5.a, < 0.6"
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: async-stream
    versions:
    - 0.3.0
