sudo: false
language: rust

rust:
  - 1.34.0  # Oldest supported
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

script:
  - cargo test --verbose

matrix:
  include:
    - env: RUSTFMT
      os: linux
      rust: 1.36.0
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
    - env: CLIPPY
      os: linux
      rust: 1.36.0
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all-features -- -D clippy::all
    - env: RUSTFLAGS="-D warnings"
      os: linux
      rust: 1.36.0
      script:
        - cargo test --verbose

cache:
  cargo: true
