language: rust
os: linux
dist: bionic

stages:
  - check
  - test
  - nightly

jobs:
  allow_failures:
    rust: nightly
  fast_finish: true
  include:

    - stage: check
      name: rustfmt
      rust: 1.41.1
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
    - name: "clippy-and-warnings"
      env: RUSTFLAGS="-D warnings"
      rust: 1.41.1
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all-features --benches --bins --examples --tests -- -D clippy::all

    - stage: test
      rust: 1.39.0  # Oldest supported
    - rust: stable
      addons:
        apt:
          packages:
            - libssl-dev
      before_cache: |
        bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      after_success: |
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
    - os: windows
      rust: stable
    - os: osx
      rust: stable

    - stage: nightly
      name: nightly
      rust: nightly

script:
  - cargo test

cache:
  cargo: true
