sudo: false
language: rust

matrix:
  include:
    - name: "rustfmt"
      os: linux
      rust: 1.36.0
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
    - name: "clippy"
      os: linux
      rust: 1.36.0
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all-features -- -D clippy::all
    - name: "fail-on-warnings"
      env: RUSTFLAGS="-D warnings"
      os: linux
      rust: 1.36.0
      script:
        - cargo test --verbose
    - name: "nightly"
      os: linux
      rust: nightly
      script:
        - cargo test --verbose

rust:
  - 1.33.0  # Oldest supported
  - stable

os:
  - linux
  - osx
  - windows

script:
  - cargo test --verbose

cache:
  cargo: true
