[package]
name = "saltlick"
version = "0.1.0"
authors = ["Nick Stevens <nick@bitcurry.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
bytes = "0.4"
lazy_static = "1.0"
pem = "0.6"
simple_asn1 = "0.4"
sodiumoxide = "0.2"

[dev-dependencies]
rand = "0.7"
rand_xorshift = "0.2"
